# Generated by Django 6.0.6 on 2026-06-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='blood_type',
            field=models.CharField(choices=[('UNKNOWN', '미입력'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='pregnancy_status',
            field=models.CharField(choices=[('NONE', '해당 없음'), ('PREGNANT', '임신 중'), ('BREASTFEEDING', '수유 중')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='allergies',
            field=models.TextField(blank=True, default='없음'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='current_medications',
            field=models.TextField(blank=True, default='없음'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='diseases',
            field=models.TextField(blank=True, default='없음'),
        ),
    ]
